# apiVersion = (Camel Case)
apiVersion: v1 
kind: Pod
metadata: 
  name: apache-pod
  labels:
# key must be unique, value can be repeated. Labels can be applied at any time. 
    env: devolopment
    tier: frontend
    app: apache
    release: stable 
spec:
  containers:
  - image: httpd
    name: apache-container
    ports:       
      - protocol: TCP     
        containerPort: 80      
